pub const BINDINGS: &[Binding] = &[

    Binding {
        keys: ":terminal :terminal-local :terminal-stop",
        desc: "launch a local PTY, explicitly choose local context, or stop and retain output",
        sections: &["terminal"],
        live: true,
        id: "terminal-lifecycle",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-\\ ctrl-n",
        desc: "terminal input → editor Normal inspection; Esc stays with the child",
        sections: &["terminal"],
        live: true,
        id: "terminal-normal",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-w h/j/k/l/w · ctrl-w N · ctrl-w .",
        desc: "from terminal input: move/cycle panes, enter inspection, or send the literal byte (vim t_CTRL-W)",
        sections: &["terminal"],
        live: true,
        id: "terminal-window",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "i a",
        desc: "terminal Normal inspection → live child input (never relaunches an exited session)",
        sections: &["terminal"],
        live: true,
        id: "terminal-input",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: ":terminal-paste :terminal-paste-cancel",
        desc: "confirm or discard the scoped held multiline/control paste",
        sections: &["terminal"],
        live: true,
        id: "terminal-paste-decision",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: ":terminal-refresh",
        desc: "reinstall the latest output into the pinned inspection snapshot (never auto-refreshes a selection)",
        sections: &["terminal"],
        live: true,
        id: "terminal-refresh",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-4 ctrl-n",
        desc: "legacy Ctrl-\\ Ctrl-N spelling from the outer terminal decoder",
        sections: &["terminal"],
        live: true,
        id: "terminal-normal-legacy",
        kind: CommandKind::Contextual,
    },
    // normal: motions
    Binding {
        keys: "h j k l",
        desc: "move (never off the line)",
        sections: &["normal"],
        live: true,
        id: "move",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "w b e W B E",
        desc: "word / WORD motions",
        sections: &["normal"],
        live: true,
        id: "word-motions",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "zz zt zb",
        desc: "center/top/bottom the cursor line",
        sections: &["normal"],
        live: true,
        id: "view-place",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "H M L",
        desc: "top/middle/bottom visible line",
        sections: &["normal"],
        live: true,
        id: "visible-jumps",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ZZ",
        desc: "write + close window",
        sections: &["normal"],
        live: true,
        id: "write-quit",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gv",
        desc: "reselect last visual",
        sections: &["normal"],
        live: true,
        id: "reselect-visual",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gi",
        desc: "insert at last insert",
        sections: &["normal"],
        live: true,
        id: "insert-at-last",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "g;",
        desc: "older change (changelist)",
        sections: &["normal"],
        live: true,
        id: "change-back",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "g,",
        desc: "newer change (changelist)",
        sections: &["normal"],
        live: true,
        id: "change-forward",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ge gE { }",
        desc: "word-end back / paragraph motions",
        sections: &["normal"],
        live: true,
        id: "paragraph-motions",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "0 $ G %",
        desc: "line/file/pair jumps",
        sections: &["normal"],
        live: true,
        id: "line-jumps",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "g<space>",
        desc: "collection: open full source at caret",
        sections: &["normal"],
        live: true,
        id: "collection-source",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gb",
        desc: "select next occurrence of word/selection",
        sections: &["normal", "visual"],
        live: true,
        id: "occurrence-next",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gB",
        desc: "select all occurrences in buffer",
        sections: &["normal", "visual"],
        live: true,
        id: "occurrence-all",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gg",
        desc: "top of file",
        sections: &["normal"],
        live: true,
        id: "top",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "enter",
        desc: "line down, first non-blank (blame gutter: dive)",
        sections: &["normal"],
        live: true,
        id: "enter",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "tab",
        desc: "jump list forward (ctrl-i)",
        sections: &["normal"],
        live: true,
        id: "jump-forward",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ctrl-r",
        desc: "redo",
        sections: &["normal"],
        live: true,
        id: "redo",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ctrl-d ctrl-u ctrl-f ctrl-b",
        desc: "half/full page scroll (count = lines)",
        sections: &["normal"],
        live: true,
        id: "scroll-pages",
        kind: CommandKind::Leaf, // count-aware: dispatch_row
    },
    Binding {
        keys: "ctrl-^",
        desc: "alternate buffer",
        sections: &["normal"],
        live: true,
        id: "alternate-buffer",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "q<a>",
        desc: "record macro into register",
        sections: &["normal"],
        live: true,
        id: "macro-record",
        kind: CommandKind::AbsorbChar(AbsorbKind::MacroRecord),
    },
    Binding {
        keys: "@<a>",
        desc: "play macro (count repeats)",
        sections: &["normal"],
        live: true,
        id: "macro-play",
        kind: CommandKind::AbsorbChar(AbsorbKind::MacroPlay),
    },
    Binding {
        keys: "gr",
        desc: "references (LSP)",
        sections: &["normal"],
        live: true,
        id: "references",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gI",
        desc: "implementation (LSP)",
        sections: &["normal"],
        live: true,
        id: "implementation",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gy",
        desc: "type definition (LSP)",
        sections: &["normal"],
        live: true,
        id: "type-definition",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gD",
        desc: "declaration (LSP)",
        sections: &["normal"],
        live: true,
        id: "declaration",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "]d [d",
        desc: "next/prev diagnostic",
        sections: &["normal"],
        live: true,
        id: "diagnostic-jumps",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gd",
        desc: "goto definition (LSP)",
        sections: &["normal"],
        live: true,
        id: "goto-definition",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "gs",
        desc: "switch source/header (clangd)",
        sections: &["normal"],
        live: true,
        id: "switch-source-header",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "f<c> F<c> t<c> T<c>",
        desc: "find/till char (candidates light up)",
        sections: &["normal"],
        live: true,
        id: "find-char",
        kind: CommandKind::AbsorbChar(AbsorbKind::Find),
    },
    Binding {
        keys: ":",
        desc: "ex command line",
        sections: &["normal"],
        live: true,
        id: "ex-line",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "/ ?",
        desc: "literal search forward / backward (live as you type or delete)",
        sections: &["normal"],
        live: true,
        id: "search",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "n",
        desc: "next match",
        sections: &["normal"],
        live: true,
        id: "search-next",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "N",
        desc: "previous match",
        sections: &["normal"],
        live: true,
        id: "search-prev",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "]f [f",
        desc: "next / prev file card (collections)",
        sections: &["normal"],
        live: true,
        id: "collection-file-nav",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "]e [e",
        desc: "next / prev excerpt (collections; +/- context)",
        sections: &["normal"],
        live: true,
        id: "collection-excerpt-nav",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "]c [c",
        desc: "next / prev git hunk",
        sections: &["normal"],
        live: true,
        id: "hunk-nav",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "m<a>",
        desc: "set mark at cursor",
        sections: &["normal"],
        live: true,
        id: "mark-set",
        kind: CommandKind::AbsorbChar(AbsorbKind::MarkSet),
    },
    Binding {
        keys: "'<a> `<a>",
        desc: "jump to mark",
        sections: &["normal"],
        live: true,
        id: "mark-jump",
        kind: CommandKind::AbsorbChar(AbsorbKind::MarkJump),
    },
    Binding {
        keys: "* #",
        desc: "word under cursor, forward / backward",
        sections: &["normal"],
        live: true,
        id: "word-search",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "; ,",
        desc: "repeat find, same / reversed",
        sections: &["normal"],
        live: true,
        id: "find-repeat",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "|",
        desc: "column motion (vim); pipe moved to space |",
        sections: &["normal"],
        live: true,
        id: "column-motion",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "space |",
        desc: "pipe line/selection through shell (:! runs)",
        sections: &["leader"],
        live: true,
        id: "pipe-shell",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "Q",
        desc: "toggle cursor at point (multicursor)",
        sections: &["normal"],
        live: true,
        id: "cursor-toggle",
        kind: CommandKind::Leaf,
    },
    // normal: operators
    Binding {
        keys: "d y c > <",
        desc: "operators + motion/object (live preview)",
        sections: &["normal"],
        live: true,
        id: "operators",
        kind: CommandKind::Operator,
    },
    Binding {
        keys: "dd yy cc",
        desc: "line delete/yank/change",
        sections: &["normal"],
        live: true,
        id: "line-ops",
        kind: CommandKind::Operator,
    },
    Binding {
        keys: "D",
        desc: "delete to line end",
        sections: &["normal"],
        live: true,
        id: "op-alias-d",
        kind: CommandKind::Alias,
    },
    Binding {
        keys: "C",
        desc: "change to line end",
        sections: &["normal"],
        live: true,
        id: "op-alias-c",
        kind: CommandKind::Alias,
    },
    Binding {
        keys: "Y",
        desc: "yank line",
        sections: &["normal"],
        live: true,
        id: "op-alias-y",
        kind: CommandKind::Alias,
    },
    Binding {
        keys: "s",
        desc: "substitute char",
        sections: &["normal"],
        live: true,
        id: "op-alias-s",
        kind: CommandKind::Alias,
    },
    Binding {
        keys: "x X",
        desc: "delete char / char back",
        sections: &["normal"],
        live: true,
        id: "char-delete",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "iw i\" i' i( i[ i{",
        desc: "inner objects (quotes scan the line)",
        sections: &["normal"],
        live: true,
        id: "objects",
        kind: CommandKind::ObjectPrefix,
    },
    Binding {
        keys: "ds\" cs\"' ysiw\"",
        desc: "surround: delete / change / add",
        sections: &["normal"],
        live: true,
        id: "surround",
        kind: CommandKind::ObjectPrefix,
    },
    Binding {
        keys: "i a A o O I",
        desc: "insert (auto-indent)",
        sections: &["normal"],
        live: true,
        id: "insert-entries",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "p P",
        desc: "paste after / before",
        sections: &["normal"],
        live: true,
        id: "paste",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "r<c>",
        desc: "replace char",
        sections: &["normal"],
        live: true,
        id: "replace-char",
        kind: CommandKind::AbsorbChar(AbsorbKind::Replace),
    },
    Binding {
        keys: "J .",
        desc: "join lines · repeat change",
        sections: &["normal"],
        live: true,
        id: "join-repeat",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "^",
        desc: "first non-blank",
        sections: &["normal"],
        live: true,
        id: "first-non-blank",
        kind: CommandKind::Motion,
    },
    Binding {
        keys: "~",
        desc: "toggle case",
        sections: &["normal"],
        live: true,
        id: "toggle-case",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "S",
        desc: "change line",
        sections: &["normal"],
        live: true,
        id: "subst-line",
        kind: CommandKind::Alias,
    },
    Binding {
        keys: "u ctrl-r",
        desc: "undo / redo (one unit per command)",
        sections: &["normal"],
        live: true,
        id: "undo-redo",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "\"+y \"+p \"+P",
        desc: "system clipboard: yank / paste after / before",
        sections: &["normal"],
        live: true,
        id: "reg-clipboard",
        kind: CommandKind::AbsorbRegister,
    },
    Binding {
        keys: "\"xy \"xp",
        desc: "named register: yank / paste",
        sections: &["normal"],
        live: true,
        id: "reg-named",
        kind: CommandKind::AbsorbRegister,
    },
    Binding {
        keys: "ctrl-v",
        desc: "visual block",
        sections: &["normal"],
        live: true,
        id: "visual-block",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "v V",
        desc: "visual / visual-line",
        sections: &["normal"],
        live: true,
        id: "visual-enter",
        kind: CommandKind::Leaf,
    },
    // visual
    Binding {
        keys: "d y c x > <",
        desc: "operate on selection",
        sections: &["visual"],
        live: true,
        id: "visual-ops",
        kind: CommandKind::Operator,
    },
    Binding {
        keys: "S<c>",
        desc: "wrap selection in pair",
        sections: &["visual"],
        live: true,
        id: "visual-surround",
        kind: CommandKind::AbsorbChar(AbsorbKind::Replace),
    },
    Binding {
        keys: "i<a> a<a>",
        desc: "objects select (vi[ works)",
        sections: &["visual"],
        live: true,
        id: "visual-objects",
        kind: CommandKind::ObjectPrefix,
    },
    Binding {
        keys: "space y",
        desc: "yank selection → clipboard",
        sections: &["visual"],
        live: true,
        id: "clip-yank",
        kind: CommandKind::Leaf,
    },
    // insert
    Binding {
        keys: "ctrl-space",
        desc: "code completion: language service + current source words",
        sections: &["insert"],
        live: true,
        id: "completion-request",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-x ctrl-o",
        desc: "language-service completion",
        sections: &["insert"],
        live: true,
        id: "completion-language",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-n ctrl-p",
        desc: "source words; choose next/previous completion",
        sections: &["insert"],
        live: true,
        id: "completion-words",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "up down",
        desc: "choose completion when open; otherwise move the caret",
        sections: &["insert"],
        live: true,
        id: "completion-arrows",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-y",
        desc: "accept choice",
        sections: &["insert"],
        live: true,
        id: "completion-accept",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-e",
        desc: "dismiss",
        sections: &["insert"],
        live: true,
        id: "completion-dismiss",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "tab",
        desc: "indent; accept completion only after deliberate selection",
        sections: &["insert"],
        live: true,
        id: "insert-tab",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "esc",
        desc: "dismiss completion and enter Normal mode in one event (one undo unit)",
        sections: &["insert"],
        live: true,
        id: "insert-esc",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "backspace",
        desc: "delete back",
        sections: &["insert"],
        live: true,
        id: "insert-bs",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "enter",
        desc: "new line (auto-indent); accept completion only after deliberate selection",
        sections: &["insert"],
        live: true,
        id: "insert-enter",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "} ] )",
        desc: "closer on indent-only line dedents",
        sections: &["insert"],
        live: true,
        id: "insert-closers",
        kind: CommandKind::Prefix,
    },
    // leader
    Binding {
        keys: "space e",
        desc: "reveal source in its Directory buffer",
        sections: &["leader"],
        live: true,
        id: "directory-reveal",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space f",
        desc: "file finder",
        sections: &["leader"],
        live: true,
        id: "files",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space o",
        desc: "open remote destination",
        sections: &["leader"],
        live: true,
        id: "remote-open",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space b",
        desc: "buffers (MRU)",
        sections: &["leader"],
        live: true,
        id: "buffers",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space /",
        desc: "Search workspace (resume investigation)",
        sections: &["leader"],
        live: true,
        id: "search",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space R",
        desc: "Search with replacement",
        sections: &["leader"],
        live: true,
        id: "replace-global",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space ?",
        desc: "help buffer",
        sections: &["leader"],
        live: true,
        id: "help",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space y",
        desc: "yank motion → system clipboard",
        sections: &["leader"],
        live: true,
        id: "clip-yank",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space p",
        desc: "paste clipboard after",
        sections: &["leader"],
        live: true,
        id: "clip-paste",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space P",
        desc: "paste clipboard before",
        sections: &["leader"],
        live: true,
        id: "clip-paste-before",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space d",
        desc: "diagnostics picker",
        sections: &["leader"],
        live: true,
        id: "diagnostics",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space k",
        desc: "hover docs",
        sections: &["leader"],
        live: true,
        id: "hover",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space a",
        desc: "context actions (code / filesystem)",
        sections: &["leader"],
        live: true,
        id: "code-actions",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space s",
        desc: "document symbols picker",
        sections: &["leader"],
        live: true,
        id: "document-symbols",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space S",
        desc: "workspace symbols picker",
        sections: &["leader"],
        live: true,
        id: "workspace-symbols",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space j",
        desc: "jumplist picker",
        sections: &["leader"],
        live: true,
        id: "jumplist-picker",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space u",
        desc: "undo-tree browser",
        sections: &["leader"],
        live: true,
        id: "undo-tree",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space c",
        desc: "cursor on next line too (multicursor)",
        sections: &["leader"],
        live: true,
        id: "cursor-stack",
        kind: CommandKind::Leaf,
    },
    // git
    Binding {
        keys: "space g",
        desc: "git…",
        sections: &["git"],
        live: true,
        id: "git-prefix",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "space g l",
        desc: "commit browser",
        sections: &["git"],
        live: true,
        id: "git-log",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g h",
        desc: "file history (visual: selected lines)",
        sections: &["git"],
        live: true,
        id: "git-file-history",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g b",
        desc: "toggle blame gutter / card",
        sections: &["git"],
        live: true,
        id: "git-blame",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g y",
        desc: "permalink: copy",
        sections: &["git"],
        live: true,
        id: "git-permalink-yank",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g o",
        desc: "permalink: open",
        sections: &["git"],
        live: true,
        id: "git-permalink-open",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g u",
        desc: "hunk: undo unstaged (restore from index)",
        sections: &["git"],
        live: true,
        id: "git-hunk-undo",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g s",
        desc: "hunk: stage (live→index)",
        sections: &["git"],
        live: true,
        id: "git-hunk-stage",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g S",
        desc: "hunk: unstage (index→HEAD)",
        sections: &["git"],
        live: true,
        id: "git-hunk-unstage",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "space g p",
        desc: "hunk: preview",
        sections: &["git"],
        live: true,
        id: "git-hunk-preview",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "]f [f",
        desc: "next / prev file in commit diff",
        sections: &["git"],
        live: true,
        id: "commit-file-nav",
        kind: CommandKind::Soon,
    },
    Binding {
        keys: "enter",
        desc: "dive into the line's commit (blame gutter)",
        sections: &["git"],
        live: true,
        id: "surface-dive",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "q",
        desc: "close surface (readonly buffers)",
        sections: &["git"],
        live: true,
        id: "surface-close",
        kind: CommandKind::Prefix,
    },
    // ex + panes
    Binding {
        keys: ":w :q :q! :wq :w {file} :trust",
        desc: "write / quit (force) / write-quit / write-as",
        sections: &["ex+panes"],
        live: true,
        id: "ex-write-quit",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: ":[range]s/a/b/[g] :N :% :N,Md :N,My",
        desc: "substitute (literal) / goto line / ranged delete+yank",
        sections: &["ex+panes"],
        live: true,
        id: "ex-ranges",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "ctrl-d ctrl-u ctrl-f ctrl-b",
        desc: "half/full page scroll (count = lines)",
        sections: &["ex+panes"],
        live: true,
        id: "scroll-pages",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: ":e",
        desc: "edit file",
        sections: &["ex+panes"],
        live: true,
        id: "ex-edit",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: ":help",
        desc: "help buffer (this text — / searches it)",
        sections: &["ex+panes"],
        live: true,
        id: "ex-help",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: ":vs :sp",
        desc: "split vertical / horizontal",
        sections: &["ex+panes"],
        live: true,
        id: "ex-split",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "ctrl-w h / l / j / k / w",
        desc: "pane move / cycle",
        sections: &["ex+panes"],
        live: true,
        id: "pane-nav",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ctrl-o / ctrl-i (tab)",
        desc: "jump back / forward (jumplist)",
        sections: &["ex+panes"],
        live: true,
        id: "jumplist",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "ctrl-w v / s",
        desc: "pane split (vs / sp)",
        sections: &["ex+panes"],
        live: true,
        id: "pane-split",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: ":view :set",
        desc: "readonly browsing (:set ro/noro; CLI: -R)",
        sections: &["ex+panes"],
        live: true,
        id: "readonly",
        kind: CommandKind::TextLine,
    },
    Binding {
        keys: "ctrl-w q",
        desc: "close pane (last → buffer)",
        sections: &["ex+panes"],
        live: true,
        id: "pane-close",
        kind: CommandKind::Leaf,
    },
    Binding {
        keys: "up down left right tab s-tab",
        desc: "picker navigation / arrows = hjkl everywhere",
        sections: &["ex+panes"],
        live: true,
        id: "picker-nav",
        kind: CommandKind::Prefix,
    },
    Binding {
        keys: "ctrl-x",
        desc: "Search: exclude/include match",
        sections: &["ex+panes"],
        live: true,
        id: "search-exclude",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-space",
        desc: "query field: qualifier, language and value suggestions",
        sections: &["ex+panes"],
        live: true,
        id: "query-suggestions",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-d",
        desc: "Search: exclude/include file",
        sections: &["ex+panes"],
        live: true,
        id: "search-file-exclude",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-r",
        desc: "Search: toggle replacement; document: redo",
        sections: &["ex+panes"],
        live: true,
        id: "search-replacement",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "enter",
        desc: "Search Find: open source; With: prepare review",
        sections: &["ex+panes"],
        live: true,
        id: "search-accept",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-o",
        desc: "Search: collect included matches",
        sections: &["ex+panes"],
        live: true,
        id: "search-collect",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: ":tab-size :indent-style :search-options",
        desc: "source indentation and search visibility controls",
        sections: &["ex+panes"],
        live: true,
        id: "source-and-search-settings",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: ":fs :browse :filter",
        desc: "filesystem actions, namespace-aware browsing and folder filtering",
        sections: &["ex+panes"],
        live: true,
        id: "filesystem",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: ":apply-change :cancel-change :save-change",
        desc: "review: apply text or filesystem changes, cancel, or save changed text",
        sections: &["ex+panes"],
        live: true,
        id: "change-review-actions",
        kind: CommandKind::Contextual,
    },
    Binding {
        keys: "ctrl-l",
        desc: "redraw: full repaint when the terminal desyncs",
        sections: &["ex+panes"],
        live: true,
        id: "redraw",
        kind: CommandKind::Leaf,
    },
];
